### ISSUE TITLE
allow other keyboard shortcuts?

### ISSUE THREAD

**Issue by loopernow** [gignupg/Search-Box-Focus#2]
"Tab" is convenient but interferes with navigation of webforms.

I've seen other extensions with shortcuts such as Esc, Ctrl+Space, "/"...

(However, these extensions don't actually focus the searchbar anymore. They are old extensions or for whatever other reason don't work well.)

**Comment by gignupg** [comment]
It's possible to create custom shortcuts!

![custom shortcut](https://user-images.githubusercontent.com/52784332/125768277-a5487e2d-53b1-4015-a8f4-5b6640c61b57.png)
![select shortcut](https://user-images.githubusercontent.com/52784332/125768307-3dad7f23-6c55-4025-b5bc-d0ed9fa9b67e.png)

**Comment by loopernow** [comment]
Oh! I'm sorry I missed the obvious but glad I posted this issue. Thank you!
